# Generated by Django 4.2.29 on 2026-04-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartao'), ('credito_interno', 'Credito Interno')], max_length=20, verbose_name='Forma de Pagamento')),
                ('janela_atendimento', models.CharField(choices=[('recreio_manha', 'Recreio Manha'), ('almoco', 'Almoco'), ('recreio_tarde', 'Recreio Tarde'), ('fora_intervalo', 'Fora de Intervalo'), ('evento_especial', 'Evento Especial')], default='fora_intervalo', max_length=20, verbose_name='Janela de Atendimento')),
                ('modo_atendimento', models.CharField(choices=[('rapido', 'Rapido'), ('normal', 'Normal'), ('pedido_antecipado', 'Pedido Antecipado')], default='rapido', max_length=20, verbose_name='Modo de Atendimento')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Bruto')),
                ('valor_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Descontos')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido')),
                ('troco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco')),
                ('vendido_em', models.DateTimeField(verbose_name='Vendido em')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacao')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-vendido_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='estoque.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
            },
        ),
    ]
