# Generated by Django 4.2.29 on 2026-04-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanelaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Janela de Atendimento',
                'verbose_name_plural': 'Janelas de Atendimento',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartão'), ('credito_interno', 'Crédito Interno')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='modo_atendimento',
            field=models.CharField(choices=[('rapido', 'Rápido'), ('normal', 'Normal'), ('pedido_antecipado', 'Pedido Antecipado')], default='rapido', max_length=20, verbose_name='Modo de Atendimento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='janela_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.janelaatendimento', verbose_name='Janela de Atendimento'),
        ),
    ]
