# Generated by Django 4.2.29 on 2026-05-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_janelaatendimento_alter_itemvenda_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='janela_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.janelaatendimento', verbose_name='Período de Atendimento'),
        ),
    ]
