# Generated by Django 4.2.29 on 2026-05-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_venda_janela_atendimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='janelaatendimento',
            options={'ordering': ['hora_inicio'], 'verbose_name': 'Período de Atendimento', 'verbose_name_plural': 'Períodos de Atendimento'},
        ),
    ]
