# Generated by Django 4.2.29 on 2026-04-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='estoque.categoria', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('codigo_barras', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Codigo de Barras')),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('lt', 'Litro'), ('pct', 'Pacote')], default='un', max_length=10, verbose_name='Unidade de Medida')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preco de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preco de Venda')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Minimo')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('operacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida'), ('ajuste', 'Ajuste')], max_length=10, verbose_name='Operacao')),
                ('origem', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('perda', 'Perda'), ('inventario', 'Inventario'), ('doacao', 'Doacao'), ('ajuste_manual', 'Ajuste Manual')], max_length=20, verbose_name='Origem')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario')),
                ('saldo_antes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Antes')),
                ('saldo_depois', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Depois')),
                ('documento_referencia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Documento de Referencia')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacao')),
                ('data_movimento', models.DateTimeField(verbose_name='Data do Movimento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
