# Generated by Django 4.2.29 on 2026-05-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_janelaatendimento_options'),
        ('estoque', '0003_add_categoria_ativo'),
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAntecipado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_aluno', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('turma', models.CharField(max_length=20, verbose_name='Turma')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('retirado', 'Retirado'), ('expirado', 'Expirado')], default='pendente', max_length=10, verbose_name='Status')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('janela_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='vendas.janelaatendimento', verbose_name='Período de Retirada')),
            ],
            options={
                'verbose_name': 'Pedido Antecipado',
                'verbose_name_plural': 'Pedidos Antecipados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agendamento.pedidoantecipado', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
