# Generated by Django 4.2.29 on 2026-05-13 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_pedidoantecipado_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoantecipado',
            name='data_atendimento',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Atendimento'),
        ),
    ]
